id = "1a"
label = "1a"
file_stem = "1a"
evalstart = "2024-07-01T10:15:00"
evalend = "2027-07-10T16:00:00"
data_root = "/home/haugened/Documents/data/CONTRASTS/EC_offline_preproc/cut/"
data_files = [
    "1a_t1_irg_proc_cut.nc",
    "1a_t1_csat_proc_cut.nc",
    "1a_t2_irg_proc_cut.nc",
    "1a_t2_csat_proc_cut.nc",
]
surface_type = ["pond", "pond", "ice", "ice"]
heights = [1.2, 2.2, 1.3, 2.2]
instrument_type = ["IRG", "CSAT", "IRG", "CSAT"]

[manual_nanmask]
enabled = true
root = "/home/haugened/Documents/data/CONTRASTS/nan_periods"
files = ["t1irg_nan.csv", "t1csat_nan.csv", "t2irg_nan.csv", "t2csat_nan.csv"]
columns = ["u", "v", "w", "T"]

[paths]
plot_root = "/home/haugened/Documents/data/CONTRASTS/plots"
presentation_root = "/home/haugened/Documents/presentation/conferences/arctic_system_26"

[plot]
heat_flux_title = "1a Turbulent Heat Fluxes"
wT_limits = [-30.0, 30.0]
wq_limits = [-15.0, 30.0]
heat_correlation_title = "1a - 09.07.2025 to 10.07.2025 16:00"

[footprint]
wind_direction_offsets = [235.0, 235.0, 215.0, 215.0]
orthomosaic = "/home/haugened/Documents/data/CONTRASTS/pics/setups/1a/karte 11072025_cut.jpg"
fluxloc = [[1024, 1050], [1024, 1050], [879, 1222], [879, 1222]]
bgextend_m = [97.7, 133.5]
bgextend_pxl = [1643, 2145]
figorigin = [1024, 1050]
