id = "1c"
label = "1c"
file_stem = "1c"
evalstart = "2023-07-27T10:10:00"
evalend = "2027-07-27T09:10:00"
data_root = "/home/haugened/Documents/data/CONTRASTS/EC_offline_preproc/cut/"
data_files = [
    "1c_t1_irg_proc_cut.nc",
    "1c_t1_csat_proc_cut.nc",
    "1c_t2_irg_proc_cut.nc",
    "1c_t2_csat_proc_cut.nc",
]
surface_type = ["lead", "lead", "ice", "ice"]
heights = [1.1, 2.2, 2.4, 1.2]
instrument_type = ["IRG", "CSAT", "IRG", "CSAT"]

[manual_nanmask]
enabled = true
root = "/home/haugened/Documents/data/CONTRASTS/nan_periods"
files = ["t1irg_nan.csv", "t1csat_nan.csv", "t2irg_nan.csv", "t2csat_nan.csv"]
columns = ["u", "v", "w", "T"]

[paths]
plot_root = "/home/haugened/Documents/data/CONTRASTS/plots"
presentation_root = "/home/haugened/Documents/presentation/conferences/arctic_system_26"

[plot]
heat_flux_title = "1c Turbulent Heat Fluxes"
wT_limits = [-20.0, 10.0]
wq_limits = [-12.0, 8.0]
heat_correlation_title = "1b position 1 pond - 25.07.2025 to 27.07.2025"

[footprint]
wind_direction_offsets = [200.0, 203.0, 167.0, 161.0]
orthomosaic = "/home/haugened/Documents/data/CONTRASTS/Orthomosaics/R1_3/13_cut.jpeg"
fluxloc = [[2375, 1360], [2375, 1360], [1916, 1520], [1916, 1520]]
figorigin = [2375, 1360]

[block_footprints]
classes_file = "/home/haugened/Documents/data/CONTRASTS/Orthomosaics/R1_3/13_cut_classes.jpeg"
feature = "lead"
crit_ice_red_bigger_eq = 222
crit_ice_red_smaller_eq = 255
crit_ice_green_bigger_eq = 222
crit_ice_green_smaller_eq = 255
crit_ice_blue_bigger_eq = 222
crit_ice_blue_smaller_eq = 255
crit_feature_red_bigger_eq = 0
crit_feature_red_smaller_eq = 1
crit_feature_green_bigger_eq = 0
crit_feature_green_smaller_eq = 1
crit_feature_blue_bigger_eq = 0
crit_feature_blue_smaller_eq = 1
wT_limits_diff_timeseries = [-10, 10]
wq_limits_diff_timeseries = [-10, 10]

[block_analysis]
subplot_order = ["fx2", "fx3", "fx1", "fx4"]
latent_subplot_order = ["fx1", "fx3"]