id = "2b"
label = "2b"
file_stem = "2b"
evalstart = "2023-07-27T10:10:00"
evalend = "2027-07-27T09:10:00"
data_root = "/home/haugened/Documents/data/CONTRASTS/EC_offline_preproc/cut/"
data_files = [
    "2b_t1_irg_proc_cut.nc",
    "2b_t1_csat_proc_cut.nc",
    "2b_t2_irg_proc_cut.nc",
    "2b_t2_csat_proc_cut.nc",
]
surface_type = ["pond", "pond", "ice", "ice"]
heights = [1.1, 2.2, 1.2, 2.2]
instrument_type = ["IRG", "CSAT", "IRG", "CSAT"]

[manual_nanmask]
enabled = true
root = "/home/haugened/Documents/data/CONTRASTS/nan_periods"
files = ["t1irg_nan.csv", "t1csat_nan.csv", "t2irg_nan.csv", "t2csat_nan.csv"]
columns = ["u", "v", "w", "T"]

[paths]
plot_root = "/home/haugened/Documents/data/CONTRASTS/plots"
presentation_root = "/home/haugened/Documents/presentation/conferences/arctic_system_26"

[plot]
heat_flux_title = "2b Turbulent Heat Fluxes"
wT_limits = [-15.0, 35.0]
wq_limits = [-1.0, 20.0]
heat_correlation_title = "1b position 1 pond - 25.07.2025 to 27.07.2025"

[footprint]
wind_direction_offsets = [270.0, 270.0, 270.0, 270.0]
orthomosaic = "/home/haugened/Documents/data/CONTRASTS/pics/setups/2b/22_cut.jpeg"
fluxloc = [[627, 1381], [627, 1381], [549, 1486], [549, 1486]]
figorigin = [627, 1381]

[block_footprints]
classes_file = "/home/haugened/Documents/data/CONTRASTS/pics/setups/2b/karte 140725_cut_classes.jpg"
feature = "pond"
crit_ice_red_bigger_eq = 222
crit_ice_red_smaller_eq = 255
crit_ice_green_bigger_eq = 222
crit_ice_green_smaller_eq = 255
crit_ice_blue_bigger_eq = 222
crit_ice_blue_smaller_eq = 255
crit_feature_red_bigger_eq = 0
crit_feature_red_smaller_eq = 1
crit_feature_green_bigger_eq = 0
crit_feature_green_smaller_eq = 1
crit_feature_blue_bigger_eq = 0
crit_feature_blue_smaller_eq = 1
wT_limits_diff_timeseries = [-10, 10]
wq_limits_diff_timeseries = [-10, 10]

[block_analysis]
subplot_order = ["fx4", "fx2", "fx3", "fx1"]
latent_subplot_order = ["fx3", "fx1"]