id = "3c"
label = "3c"
file_stem = "3c"
evalstart = "2023-07-27T10:10:00"
evalend = "2027-07-27T09:10:00"
data_root = "/home/haugened/Documents/data/CONTRASTS/EC_offline_preproc/cut/"
data_files = [
    "3c_t1_irg_proc_cut.nc",
    "3c_t1_csat_proc_cut.nc",
    "3c_t2_irg_proc_cut.nc",
    "3c_t2_csat_proc_cut.nc",
]
surface_type = ["lead", "lead", "floe", "floe"]
heights = [1.1, 2.2, 1.1, 2.2]
instrument_type = ["IRG", "CSAT", "IRG", "CSAT"]

[flux_histogram]
surface_type = ["lead", "lead", "ridge", "ridge"]
flow_across_ridge_interval = [155, 335]

[manual_nanmask]
enabled = true
root = "/home/haugened/Documents/data/CONTRASTS/nan_periods"
files = ["t1irg_nan.csv", "t1csat_nan.csv", "t2irg_nan.csv", "t2csat_nan.csv"]
columns = ["u", "v", "w", "T"]

[paths]
plot_root = "/home/haugened/Documents/data/CONTRASTS/plots"
presentation_root = "/home/haugened/Documents/presentation/conferences/arctic_system_26"

[plot]
heat_flux_title = "3c Turbulent Heat Fluxes - Across Ridge"
wT_limits = [-50.0, 30.0]
wq_limits = [-15.0, 25.0]
heat_correlation_title = "3c - 16.08.2025 to 18.08.2025"

[footprint]
wind_direction_offsets = [206.0, 218.0, 228.0, 238.0]
orthomosaic = "/home/haugened/Documents/data/CONTRASTS/Orthomosaics/R3_3/33_cut.jpeg"
fluxloc = [[1458, 1533], [1458, 1533], [1057, 2108], [1057, 2108]]
figorigin = [1458, 1533]

[block_footprints]
classes_file = "/home/haugened/Documents/data/CONTRASTS/Orthomosaics/R3_3/33_cut_classes.jpeg"
feature = "ridge"
crit_ice_red_bigger_eq = 222
crit_ice_red_smaller_eq = 255
crit_ice_green_bigger_eq = 222
crit_ice_green_smaller_eq = 255
crit_ice_blue_bigger_eq = 222
crit_ice_blue_smaller_eq = 255
crit_feature_red_bigger_eq = 0
crit_feature_red_smaller_eq = 1
crit_feature_green_bigger_eq = 0
crit_feature_green_smaller_eq = 1
crit_feature_blue_bigger_eq = 100
crit_feature_blue_smaller_eq = 255
wT_limits_diff_timeseries = [-20, 20]
wq_limits_diff_timeseries = [-15, 5]

[block_analysis]
subplot_order = ["fx2", "fx4", "fx1", "fx3"]
latent_subplot_order = ["fx1", "fx3"]
