id = "3d"
label = "3d"
file_stem = "3d"
evalstart = "2023-07-27T10:10:00"
evalend = "2027-07-27T09:10:00"
data_root = "/home/haugened/Documents/data/CONTRASTS/EC_offline_preproc/cut/"
data_files = [
    "3d_t1_irg_proc_cut.nc",
    "3d_t1_csat_proc_cut.nc",
    "3d_t2_irg_proc_cut.nc",
    "3d_t2_csat_proc_cut.nc",
]
surface_type = ["lead", "lead", "floe", "floe"]
heights = [1.1, 2.2, 1.0, 2.1]
instrument_type = ["IRG", "CSAT", "IRG", "CSAT"]

[flux_histogram]
surface_type = ["ice", "ice", "ice", "ice"]

[[wind_direction_rotations]]
instrument_indices = [1, 2]
start = "2025-08-27T08:40:00"
offset_degrees = 95.0

[[wind_direction_rotations]]
instrument_indices = [3, 4]
start = "2025-08-27T09:03:00"
offset_degrees = 60.0

[manual_nanmask]
enabled = true
root = "/home/haugened/Documents/data/CONTRASTS/nan_periods"
files = ["t1irg_nan.csv", "t1csat_nan.csv", "t2irg_nan.csv", "t2csat_nan.csv"]
columns = ["u", "v", "w", "T"]

[paths]
plot_root = "/home/haugened/Documents/data/CONTRASTS/plots"
presentation_root = "/home/haugened/Documents/presentation/conferences/arctic_system_26"

[plot]
heat_flux_title = "3d Turbulent Heat Fluxes - Across Ridge"
wT_limits = [-10.0, 10.0]
wq_limits = [-4.0, 4.0]
heat_correlation_title = "3c - 16.08.2025 to 18.08.2025"

[footprint]
wind_direction_offsets = [21.5, 28.5, 65.0, 65.0]
orthomosaic = "/home/haugened/Documents/data/CONTRASTS/Orthomosaics/R3_4/34_cut.jpeg"
fluxloc = [[3177, 3491], [3177, 3491], [3129, 3953], [3129, 3953]]
figorigin = [3177, 3491]

[block_footprints]
classes_file = "/home/haugened/Documents/data/CONTRASTS/Orthomosaics/R3_1/31_cut_classes.jpeg"
feature = "ridge"
crit_ice_red_bigger_eq = 222
crit_ice_red_smaller_eq = 255
crit_ice_green_bigger_eq = 222
crit_ice_green_smaller_eq = 255
crit_ice_blue_bigger_eq = 222
crit_ice_blue_smaller_eq = 255
crit_feature_red_bigger_eq = 0
crit_feature_red_smaller_eq = 1
crit_feature_green_bigger_eq = 0
crit_feature_green_smaller_eq = 1
crit_feature_blue_bigger_eq = 100
crit_feature_blue_smaller_eq = 255
wT_limits_diff_timeseries = [-20, 20]
wq_limits_diff_timeseries = [-5, 5]

[block_analysis]
subplot_order = ["fx4", "fx2", "fx3", "fx1"]
latent_subplot_order = ["fx3", "fx1"]
